name: Check and Deploy Bicep Template
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write # Require write permission to Fetch an OIDC token.
  actions: read # Required if repo is private
  contents: read # Required if repo is private
  security-events: write # Required for code scanning

env:
  rgName: rg-uks-sandbox-pmc-github-testing
  location: uksouth
  costTag: "Cost Centre=Training"
  serviceTag: "Service=Training"
  createdTag: "Created By=Paul McCormack"

jobs:
  check-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Setup Bicep
      uses: anthony-c-martin/setup-bicep@v0.3

    - name: Lint Bicep
      run: |
        bicep lint ./main.bicep --diagnostics-format sarif > bicep.sarif
      
    - name: Upload Sarif
      if: (success() || failure())
      uses: github/codeql-action/upload-sarif@v3
      with:
        category: bicep
        sarif_file: bicep.sarif
    
    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{secrets.AZURE_CLIENT_ID}}
        tenant-id: ${{secrets.AZURE_TENANT_ID}}
        subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}} 
        enable-AzPSSession: true
    
    - name: Create Resource Group
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az group create --name ${{env.rgName}} --location ${{env.location}} --tags "${{env.costTag}}" "${{env.serviceTag}}" "${{env.createdTag}}"

    - name: Deploy Resources
      uses: azure/powershell@v2
      with:
        azPSVersion: latest
        inlineScript: |
          New-AzResourceGroupDeployment -Name deployStorageAccount -ResourceGroupName ${{env.rgName}} -TemplateFile ./main.bicep
